server:
  privateport: 3081
  publicport: 8081
  https:
    cert:
    key:
  edition: local-ce:dev
  debug: true
log:
  external: false
  otelcollector:
    host: otel-collector
    port: 8095
instillcloud:
  host: instill-cloud
  publicport: 443
  https:
    cert:
    key:
